# Running MicroK8s on some ARM hardware may run into difficulties because cgroups
# (required!) are not enabled by default
# https://microk8s.io/docs/install-alternatives#heading--arm
---
- hosts: ubuntu
  become: yes
  tasks:
  - name: Set cgroups
    lineinfile:
      path: /boot/firmware/cmdline.txt
      regexp: '^net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc$'
      state: present
      line: net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=memory cgroup_memory=1