# Set hostnames playbook
---
- hosts: ubuntu
  become: yes
  tasks:
  - name: "update hostnames"
    hostname:
      name: "{{ inventory_hostname }}"
  - name: "reboot"
    reboot:
    when: ansible_facts['hostname'] != inventory_hostname