# Install a snap with classic confinement
---
- hosts: ubuntu
  become: yes
  tasks:
  - name: snap install microk8s --classic --channel=latest/stable
    community.general.snap:
      name: microk8s
      classic: yes
      channel: latest/stable
  - name: Append the group 'microk8s' to `ubuntu` user's groups (usermod -a -G microk8s ubuntu)
    user:
      name: ubuntu
      groups: microk8s
      append: yes
  - name: Change file ownership, group and permissions (chown -f -R ubuntu ~/.kube)
    file:
      path: ~/.kube
      recurse: yes
      owner: ubuntu
  - name: microk8s status --wait-ready
    command: microk8s status --wait-ready
    timeout: 300